######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 23 02:45:42 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mvform.h mvscene.h
FORMS += mainform.ui
SOURCES += main.cpp mvform.cpp mvscene.cpp

OTHER_FILES +=








